### ISSUE TITLE
ImportError: bad magic number in 'pinax_theme_bootstrap': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by grahamu** [pinax/cloudspotting#2]
When I invoke

```
$ coverage run setup.py test
```

the result is `ImportError: bad magic number in 'pinax_theme_bootstrap': b'\x03\xf3\r\n'`.

Does anyone else see this problem? Could this be a problem with the pinax-theme-bootstrap package?

**Comment by paltman** [comment]
I believe you have stale `*.pyc` files.

Run:

    find . -name "*.pyc" -exec rm -rf {} \;

And see if that helps.

**Comment by grahamu** [comment]
You are correct kind sir.
